#!/bin/sh
set -eu

for arg in "$@"; do
    case "$arg" in
        bin/console|./bin/console|/var/www/html/bin/console)
            export XDEBUG_TRIGGER="${XDEBUG_TRIGGER:-1}"
            break
            ;;
    esac
done

exec /usr/local/bin/php-real "$@"
