services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./:/var/www/html
      - user_photos_data:/var/www/html/public/uploads/user-photos
      - game_photos_data:/var/www/html/public/uploads/game-photos
    environment:
      APP_ENV: dev
      APP_DEBUG: "1"
      DATABASE_URL: postgresql://${POSTGRES_USER:-app}:${POSTGRES_PASSWORD:-app}@postgres:5432/${POSTGRES_DB:-app}?serverVersion=17&charset=utf8
      PHP_IDE_CONFIG: serverName=scrabble-stats-api
      REDIS_URL: redis://redis:6379

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    restart: unless-stopped
    depends_on:
      - php
    ports:
      - "8081:80"
    volumes:
      - ./public:/var/www/html/public:ro
      - user_photos_data:/var/www/html/public/uploads/user-photos:ro
      - game_photos_data:/var/www/html/public/uploads/game-photos:ro

  postgres:
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_USER: ${POSTGRES_USER:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-app}
    ports:
      - "5433:5432" #5432 is taken by wotb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  postgres_data:
  user_photos_data:
  game_photos_data:
  redis_data:
