<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260312130000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create game_photo table for tournament game uploads.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE game_photo (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, tournament_game_id INT NOT NULL, uploaded_by_player_id INT NOT NULL, category VARCHAR(16) NOT NULL, path VARCHAR(255) NOT NULL, uploaded_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_game_photo_tournament_game ON game_photo (tournament_game_id)');
        $this->addSql('CREATE INDEX idx_game_photo_uploaded_by ON game_photo (uploaded_by_player_id)');
        $this->addSql('CREATE INDEX idx_game_photo_category ON game_photo (category)');
        $this->addSql('ALTER TABLE game_photo ADD CONSTRAINT FK_FD8D7C251892790 FOREIGN KEY (tournament_game_id) REFERENCES tournament_game (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE game_photo ADD CONSTRAINT FK_FD8D7C2DC26B6A1 FOREIGN KEY (uploaded_by_player_id) REFERENCES player (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE game_photo DROP CONSTRAINT FK_FD8D7C251892790');
        $this->addSql('ALTER TABLE game_photo DROP CONSTRAINT FK_FD8D7C2DC26B6A1');
        $this->addSql('DROP TABLE game_photo');
    }
}
