<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260309170000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create unified PostgreSQL schema for organization-based data model with temporary legacy_* columns for MySQL migration.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE organization (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(64) NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_organization_code ON organization (code)');

        $this->addSql('CREATE TABLE player (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name_show VARCHAR(40) DEFAULT NULL, name_alph VARCHAR(40) DEFAULT NULL, utype VARCHAR(1) DEFAULT NULL, cached VARCHAR(1) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_player_name_alph ON player (name_alph)');

        $this->addSql('CREATE TABLE player_organization (player_id INT NOT NULL, organization_id INT NOT NULL, PRIMARY KEY(player_id, organization_id))');
        $this->addSql('CREATE INDEX IDX_96515C7999E6F5DF ON player_organization (player_id)');
        $this->addSql('CREATE INDEX IDX_96515C7932C8A3DE ON player_organization (organization_id)');
        $this->addSql('ALTER TABLE player_organization ADD CONSTRAINT FK_96515C7999E6F5DF FOREIGN KEY (player_id) REFERENCES player (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE player_organization ADD CONSTRAINT FK_96515C7932C8A3DE FOREIGN KEY (organization_id) REFERENCES organization (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('CREATE TABLE series (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, organization_id INT NOT NULL, legacy_id INT DEFAULT NULL, name VARCHAR(100) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_series_org_legacy_id ON series (organization_id, legacy_id)');
        $this->addSql('CREATE INDEX IDX_D8FBCBE232C8A3DE ON series (organization_id)');
        $this->addSql('ALTER TABLE series ADD CONSTRAINT FK_D8FBCBE232C8A3DE FOREIGN KEY (organization_id) REFERENCES organization (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('CREATE TABLE tournament (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, organization_id INT NOT NULL, winner_player_id INT DEFAULT NULL, series_id INT DEFAULT NULL, legacy_id INT DEFAULT NULL, dt INT NOT NULL, name VARCHAR(40) DEFAULT NULL, fullname VARCHAR(80) DEFAULT NULL, legacy_winner_player_id INT DEFAULT NULL, trank DOUBLE PRECISION DEFAULT NULL, players_count INT DEFAULT NULL, rounds INT DEFAULT NULL, rrecreated VARCHAR(1) DEFAULT NULL, team VARCHAR(1) DEFAULT NULL, mcategory INT DEFAULT NULL, wksum DOUBLE PRECISION DEFAULT NULL, legacy_series_id INT DEFAULT NULL, start_round INT DEFAULT NULL, referee VARCHAR(40) DEFAULT NULL, place VARCHAR(256) DEFAULT NULL, organizer VARCHAR(256) DEFAULT NULL, urlid INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_tournament_org_legacy_id ON tournament (organization_id, legacy_id)');
        $this->addSql('CREATE INDEX idx_tournament_org_dt ON tournament (organization_id, dt)');
        $this->addSql('CREATE INDEX idx_tournament_org_urlid ON tournament (organization_id, urlid)');
        $this->addSql('CREATE INDEX IDX_BD5B8E6F32C8A3DE ON tournament (organization_id)');
        $this->addSql('CREATE INDEX IDX_BD5B8E6FFB6A78E6 ON tournament (winner_player_id)');
        $this->addSql('CREATE INDEX IDX_BD5B8E6F5272486A ON tournament (series_id)');
        $this->addSql('ALTER TABLE tournament ADD CONSTRAINT FK_BD5B8E6F32C8A3DE FOREIGN KEY (organization_id) REFERENCES organization (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE tournament ADD CONSTRAINT FK_BD5B8E6FFB6A78E6 FOREIGN KEY (winner_player_id) REFERENCES player (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE tournament ADD CONSTRAINT FK_BD5B8E6F5272486A FOREIGN KEY (series_id) REFERENCES series (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('CREATE TABLE play_summary (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, organization_id INT NOT NULL, player_id INT DEFAULT NULL, legacy_player_id INT DEFAULT NULL, stype INT NOT NULL, gwin INT DEFAULT NULL, glost INT DEFAULT NULL, gdraw INT DEFAULT NULL, games INT DEFAULT NULL, gwinnw INT DEFAULT NULL, glostnw INT DEFAULT NULL, gdrawnw INT DEFAULT NULL, gamesnw INT DEFAULT NULL, gwin130 INT DEFAULT NULL, games130 INT DEFAULT NULL, gwin110 INT DEFAULT NULL, games110 INT DEFAULT NULL, gwin100 INT DEFAULT NULL, games100 INT DEFAULT NULL, over350 INT DEFAULT NULL, over400 INT DEFAULT NULL, over500 INT DEFAULT NULL, over600 INT DEFAULT NULL, grank DOUBLE PRECISION DEFAULT NULL, points DOUBLE PRECISION DEFAULT NULL, pointo DOUBLE PRECISION DEFAULT NULL, pointsw DOUBLE PRECISION DEFAULT NULL, pointow DOUBLE PRECISION DEFAULT NULL, pointsl DOUBLE PRECISION DEFAULT NULL, pointol DOUBLE PRECISION DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_play_summary_org_player_stype ON play_summary (organization_id, player_id, stype)');
        $this->addSql('CREATE INDEX idx_play_summary_org_legacy_player_stype ON play_summary (organization_id, legacy_player_id, stype)');
        $this->addSql('CREATE INDEX IDX_87316FB132C8A3DE ON play_summary (organization_id)');
        $this->addSql('CREATE INDEX IDX_87316FB199E6F5DF ON play_summary (player_id)');
        $this->addSql('ALTER TABLE play_summary ADD CONSTRAINT FK_87316FB132C8A3DE FOREIGN KEY (organization_id) REFERENCES organization (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE play_summary ADD CONSTRAINT FK_87316FB199E6F5DF FOREIGN KEY (player_id) REFERENCES player (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('CREATE TABLE ranking (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, organization_id INT NOT NULL, player_id INT DEFAULT NULL, tournament_id INT DEFAULT NULL, rtype VARCHAR(1) NOT NULL, legacy_player_id INT DEFAULT NULL, legacy_tournament_id INT DEFAULT NULL, position INT NOT NULL, rank DOUBLE PRECISION NOT NULL, games INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_ranking_org_rtype_player_tournament ON ranking (organization_id, rtype, player_id, tournament_id)');
        $this->addSql('CREATE INDEX idx_ranking_org_rtype_tournament_pos ON ranking (organization_id, rtype, tournament_id, position)');
        $this->addSql('CREATE INDEX idx_ranking_org_rtype_legacy_player_tournament ON ranking (organization_id, rtype, legacy_player_id, legacy_tournament_id)');
        $this->addSql('CREATE INDEX IDX_DD69866732C8A3DE ON ranking (organization_id)');
        $this->addSql('CREATE INDEX IDX_DD69866799E6F5DF ON ranking (player_id)');
        $this->addSql('CREATE INDEX IDX_DD6986675F12B68A ON ranking (tournament_id)');
        $this->addSql('ALTER TABLE ranking ADD CONSTRAINT FK_DD69866732C8A3DE FOREIGN KEY (organization_id) REFERENCES organization (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE ranking ADD CONSTRAINT FK_DD69866799E6F5DF FOREIGN KEY (player_id) REFERENCES player (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE ranking ADD CONSTRAINT FK_DD6986675F12B68A FOREIGN KEY (tournament_id) REFERENCES tournament (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('CREATE TABLE tournament_result (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, organization_id INT NOT NULL, tournament_id INT DEFAULT NULL, player_id INT DEFAULT NULL, legacy_tournament_id INT DEFAULT NULL, legacy_player_id INT DEFAULT NULL, place INT NOT NULL, gwin INT DEFAULT NULL, glost INT DEFAULT NULL, gdraw INT DEFAULT NULL, games INT DEFAULT NULL, trank DOUBLE PRECISION DEFAULT NULL, brank DOUBLE PRECISION DEFAULT NULL, points DOUBLE PRECISION DEFAULT NULL, pointo DOUBLE PRECISION DEFAULT NULL, hostgames INT DEFAULT NULL, hostwin INT DEFAULT NULL, masters INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_tournament_result_org_tournament_player ON tournament_result (organization_id, tournament_id, player_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_tournament_result_org_tournament_place_player ON tournament_result (organization_id, tournament_id, place, player_id)');
        $this->addSql('CREATE INDEX idx_tournament_result_org_legacy_tournament_player ON tournament_result (organization_id, legacy_tournament_id, legacy_player_id)');
        $this->addSql('CREATE INDEX IDX_57D95C1832C8A3DE ON tournament_result (organization_id)');
        $this->addSql('CREATE INDEX IDX_57D95C185F12B68A ON tournament_result (tournament_id)');
        $this->addSql('CREATE INDEX IDX_57D95C1899E6F5DF ON tournament_result (player_id)');
        $this->addSql('ALTER TABLE tournament_result ADD CONSTRAINT FK_57D95C1832C8A3DE FOREIGN KEY (organization_id) REFERENCES organization (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE tournament_result ADD CONSTRAINT FK_57D95C185F12B68A FOREIGN KEY (tournament_id) REFERENCES tournament (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE tournament_result ADD CONSTRAINT FK_57D95C1899E6F5DF FOREIGN KEY (player_id) REFERENCES player (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('CREATE TABLE tournament_game (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, organization_id INT NOT NULL, tournament_id INT DEFAULT NULL, player1_id INT DEFAULT NULL, player2_id INT DEFAULT NULL, legacy_tournament_id INT DEFAULT NULL, round_no INT NOT NULL, table_no INT DEFAULT NULL, legacy_player1_id INT DEFAULT NULL, legacy_player2_id INT DEFAULT NULL, result1 INT NOT NULL, result2 INT NOT NULL, ranko INT DEFAULT NULL, host INT DEFAULT NULL, gcg TEXT DEFAULT NULL, gcg_updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_tournament_game_org_tournament_round_players ON tournament_game (organization_id, tournament_id, round_no, player1_id, player2_id)');
        $this->addSql('CREATE INDEX idx_tournament_game_org_player1_player2 ON tournament_game (organization_id, player1_id, player2_id)');
        $this->addSql('CREATE INDEX idx_tournament_game_org_legacy_tournament_round_players ON tournament_game (organization_id, legacy_tournament_id, round_no, legacy_player1_id, legacy_player2_id)');
        $this->addSql('CREATE INDEX IDX_7BA3B4A732C8A3DE ON tournament_game (organization_id)');
        $this->addSql('CREATE INDEX IDX_7BA3B4A75F12B68A ON tournament_game (tournament_id)');
        $this->addSql('CREATE INDEX IDX_7BA3B4A7FD3A386 ON tournament_game (player1_id)');
        $this->addSql('CREATE INDEX IDX_7BA3B4A7A6CC7A2E ON tournament_game (player2_id)');
        $this->addSql('ALTER TABLE tournament_game ADD CONSTRAINT FK_7BA3B4A732C8A3DE FOREIGN KEY (organization_id) REFERENCES organization (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE tournament_game ADD CONSTRAINT FK_7BA3B4A75F12B68A FOREIGN KEY (tournament_id) REFERENCES tournament (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE tournament_game ADD CONSTRAINT FK_7BA3B4A7FD3A386 FOREIGN KEY (player1_id) REFERENCES player (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE tournament_game ADD CONSTRAINT FK_7BA3B4A7A6CC7A2E FOREIGN KEY (player2_id) REFERENCES player (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('CREATE TABLE text_resource (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, organization_id INT NOT NULL, resource_type INT NOT NULL, legacy_id INT DEFAULT NULL, data TEXT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_text_resource_org_type_legacy_id ON text_resource (organization_id, resource_type, legacy_id)');
        $this->addSql('CREATE INDEX IDX_8138A19632C8A3DE ON text_resource (organization_id)');
        $this->addSql('ALTER TABLE text_resource ADD CONSTRAINT FK_8138A19632C8A3DE FOREIGN KEY (organization_id) REFERENCES organization (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');

    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE play_summary DROP CONSTRAINT FK_87316FB132C8A3DE');
        $this->addSql('ALTER TABLE play_summary DROP CONSTRAINT FK_87316FB199E6F5DF');
        $this->addSql('ALTER TABLE player_organization DROP CONSTRAINT FK_96515C7999E6F5DF');
        $this->addSql('ALTER TABLE player_organization DROP CONSTRAINT FK_96515C7932C8A3DE');
        $this->addSql('ALTER TABLE ranking DROP CONSTRAINT FK_DD69866732C8A3DE');
        $this->addSql('ALTER TABLE ranking DROP CONSTRAINT FK_DD69866799E6F5DF');
        $this->addSql('ALTER TABLE ranking DROP CONSTRAINT FK_DD6986675F12B68A');
        $this->addSql('ALTER TABLE series DROP CONSTRAINT FK_D8FBCBE232C8A3DE');
        $this->addSql('ALTER TABLE text_resource DROP CONSTRAINT FK_8138A19632C8A3DE');
        $this->addSql('ALTER TABLE tournament DROP CONSTRAINT FK_BD5B8E6F32C8A3DE');
        $this->addSql('ALTER TABLE tournament DROP CONSTRAINT FK_BD5B8E6FFB6A78E6');
        $this->addSql('ALTER TABLE tournament DROP CONSTRAINT FK_BD5B8E6F5272486A');
        $this->addSql('ALTER TABLE tournament_game DROP CONSTRAINT FK_7BA3B4A732C8A3DE');
        $this->addSql('ALTER TABLE tournament_game DROP CONSTRAINT FK_7BA3B4A75F12B68A');
        $this->addSql('ALTER TABLE tournament_game DROP CONSTRAINT FK_7BA3B4A7FD3A386');
        $this->addSql('ALTER TABLE tournament_game DROP CONSTRAINT FK_7BA3B4A7A6CC7A2E');
        $this->addSql('ALTER TABLE tournament_result DROP CONSTRAINT FK_57D95C1832C8A3DE');
        $this->addSql('ALTER TABLE tournament_result DROP CONSTRAINT FK_57D95C185F12B68A');
        $this->addSql('ALTER TABLE tournament_result DROP CONSTRAINT FK_57D95C1899E6F5DF');

        $this->addSql('DROP TABLE play_summary');
        $this->addSql('DROP TABLE player_organization');
        $this->addSql('DROP TABLE ranking');
        $this->addSql('DROP TABLE series');
        $this->addSql('DROP TABLE text_resource');
        $this->addSql('DROP TABLE tournament');
        $this->addSql('DROP TABLE tournament_game');
        $this->addSql('DROP TABLE tournament_result');
        $this->addSql('DROP TABLE player');
        $this->addSql('DROP TABLE organization');
    }
}
