<?php

namespace App\Service\Stats;

use App\ApiResource\Stats\AllTimeSummary;
use App\ApiResource\Stats\AllTimesResults;
use App\ApiResource\Stats\AvgOpponentsPointsPerGame;
use App\ApiResource\Stats\AvgPointsSumPerGame;
use App\ApiResource\Stats\AvgPointsDifferencePerGame;
use App\ApiResource\Stats\AvgPointsPerGame;
use App\ApiResource\Stats\GamesCount;
use App\ApiResource\Stats\GamesOver400;
use App\ApiResource\Stats\DifferentOpponents;
use App\ApiResource\Stats\MostSmallPoints;
use App\ApiResource\Stats\LeastSmallPoints;
use App\ApiResource\Stats\HighestPointsSum;
use App\ApiResource\Stats\LowestPointsSum;
use App\ApiResource\Stats\HighestVictory;
use App\ApiResource\Stats\HighestDraw;
use App\ApiResource\Stats\MostPointsAndLoss;
use App\ApiResource\Stats\LeastPointsAndWin;
use App\ApiResource\Stats\MostOpponentPointsAndWin;
use App\ApiResource\Stats\LeastOpponentPointsAndLoss;
use App\ApiResource\Stats\LongestWinStreaks;
use App\ApiResource\Stats\LongestLossStreaks;
use App\ApiResource\Stats\LongestStreakMin350;
use App\ApiResource\Stats\LongestStreakMin400;
use App\ApiResource\Stats\LongestStreakSumMin750;
use App\ApiResource\Stats\LongestStreakSumMin800;
use App\ApiResource\Stats\LongestWinStreakVsPlayer;
use App\ApiResource\Stats\HighestTournamentRankRecord;
use App\ApiResource\Stats\LowestTournamentRankRecord;
use App\ApiResource\Stats\HighestAvgSmallPoints;
use App\ApiResource\Stats\LowestAvgSmallPoints;
use App\ApiResource\Stats\HighestAvgPointsSum;
use App\ApiResource\Stats\LowestAvgPointsSum;
use App\ApiResource\Stats\HighestAvgPointsDiff;
use App\ApiResource\Stats\LowestAvgPointsDiff;
use App\ApiResource\Stats\YearlyRankingSummary;
use App\ApiResource\Stats\RankAllGames;
use App\ApiResource\Stats\HighestRank;
use App\ApiResource\Stats\HighestRankPosition;
use App\ApiResource\Stats\RankingLeaders;
use App\ApiResource\Stats\GamesWon;
use App\ApiResource\Stats\TournamentsCount;

interface StatsServiceInterface
{
    public function getAllTimesResults(int $orgId): AllTimesResults;
    public function getYearlyAllTimesResults(int $year): AllTimesResults;
    public function getYearlyRankingSummary(int $year): YearlyRankingSummary;
    public function getAllTimeSummary(int $orgId): AllTimeSummary;
    public function getGamesCount(): GamesCount;
    public function getGamesWon(): GamesWon;
    public function getTournamentsCount(): TournamentsCount;
    public function getAvgPointsPerGame(): AvgPointsPerGame;
    public function getAvgOpponentsPointsPerGame(): AvgOpponentsPointsPerGame;
    public function getAvgPointsSumPerGame(): AvgPointsSumPerGame;
    public function getAvgPointsDifferencePerGame(): AvgPointsDifferencePerGame;
    public function getGamesOver400(): GamesOver400;
    public function getRankAllGames(): RankAllGames;
    public function getHighestRank(): HighestRank;
    public function getHighestRankPosition(): HighestRankPosition;
    public function getRankingLeaders(): RankingLeaders;
    public function getDifferentOpponents(): DifferentOpponents;
    public function getMostSmallPoints(): MostSmallPoints;
    public function getLeastSmallPoints(): LeastSmallPoints;
    public function getHighestPointsSum(): HighestPointsSum;
    public function getLowestPointsSum(): LowestPointsSum;
    public function getHighestVictory(): HighestVictory;
    public function getHighestDraw(): HighestDraw;
    public function getMostPointsAndLoss(): MostPointsAndLoss;
    public function getLeastPointsAndWin(): LeastPointsAndWin;
    public function getMostOpponentPointsAndWin(): MostOpponentPointsAndWin;
    public function getLeastOpponentPointsAndLoss(): LeastOpponentPointsAndLoss;
    public function getLongestWinStreaks(): LongestWinStreaks;
    public function getLongestLossStreaks(): LongestLossStreaks;
    public function getLongestStreakMin350(): LongestStreakMin350;
    public function getLongestStreakMin400(): LongestStreakMin400;
    public function getLongestStreakSumMin750(): LongestStreakSumMin750;
    public function getLongestStreakSumMin800(): LongestStreakSumMin800;
    public function getLongestWinStreakVsPlayer(): LongestWinStreakVsPlayer;
    public function getHighestTournamentRankRecord(): HighestTournamentRankRecord;
    public function getLowestTournamentRankRecord(): LowestTournamentRankRecord;
    public function getHighestAvgSmallPoints(): HighestAvgSmallPoints;
    public function getLowestAvgSmallPoints(): LowestAvgSmallPoints;
    public function getHighestAvgPointsSum(): HighestAvgPointsSum;
    public function getLowestAvgPointsSum(): LowestAvgPointsSum;
    public function getHighestAvgPointsDiff(): HighestAvgPointsDiff;
    public function getLowestAvgPointsDiff(): LowestAvgPointsDiff;
}
