# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    app.tournament_round_tokens: '%env(csv:TOURNAMENT_ROUND_TOKENS)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    app.dataset_cache:
        class: App\Service\DatasetCache

    App\Ranking\Infrastructure\GamesDataSource: '@App\Ranking\Infrastructure\GamesRepository'

    App\Service\AnnotatedGameDetails\AnnotatedGameDetailsServiceInterface: '@App\Service\AnnotatedGameDetails\AnnotatedGameDetailsServicePostgres'
    App\Service\AnnotatedGames\AnnotatedGamesServiceInterface: '@App\Service\AnnotatedGames\AnnotatedGamesServicePostgres'
    App\Service\Clubs\ClubsServiceInterface: '@App\Service\Clubs\ClubsServicePostgres'
    App\Service\OldMethodCurrentRanking\OldMethodCurrentRankingServiceInterface: '@App\Service\OldMethodCurrentRanking\OldMethodCurrentRankingServicePostgres'
    App\Service\PfsPlayerResolver\PfsPlayerResolverInterface: '@App\Service\PfsPlayerResolver\PfsPlayerResolverPostgres'
    App\Service\PfsTournamentImportCheck\PfsTournamentImportCheckServiceInterface: '@App\Service\PfsTournamentImportCheck\PfsTournamentImportCheckServicePostgres'
    App\Service\PfsTournamentImportComparer\PfsTournamentImportComparerInterface: '@App\Service\PfsTournamentImportComparer\PfsTournamentImportComparerPostgres'
    App\Service\PlayerGameBalance\PlayerGameBalanceServiceInterface: '@App\Service\PlayerGameBalance\PlayerGameBalanceServicePostgres'
    App\Service\PlayerList\PlayerListServiceInterface: '@App\Service\PlayerList\PlayerListServicePostgres'
    App\Service\PlayerProfile\PlayerProfileServiceInterface: '@App\Service\PlayerProfile\PlayerProfileServicePostgres'
    App\Service\PlayerRankHistory\PlayerRankHistoryServiceInterface: '@App\Service\PlayerRankHistory\PlayerRankHistoryServicePostgres'
    App\Service\PlayerRecords\PlayerRecordsServiceInterface: '@App\Service\PlayerRecords\PlayerRecordsServicePostgres'
    App\Service\PlayerTournamentSummary\PlayerTournamentSummaryServiceInterface: '@App\Service\PlayerTournamentSummary\PlayerTournamentSummaryServicePostgres'
    App\Service\PlayerTournaments\PlayerTournamentsServiceInterface: '@App\Service\PlayerTournaments\PlayerTournamentsServicePostgres'
    App\Service\Ranking\RankingServiceInterface: '@App\Service\Ranking\RankingServicePostgres'
    App\Service\RankingSnapshot\RankingSnapshotServiceInterface: '@App\Service\RankingSnapshot\RankingSnapshotServicePostgres'
    App\Service\Stats\StatsServiceInterface: '@App\Service\Stats\StatsServicePostgres'
    App\Service\TournamentDetails\TournamentDetailsServiceInterface: '@App\Service\TournamentDetails\TournamentDetailsServicePostgres'
    App\Service\TournamentList\TournamentListServiceInterface: '@App\Service\TournamentList\TournamentListServicePostgres'
    App\Service\TournamentRoundTokenAuthorizer:
        arguments:
            $validTokens: '%app.tournament_round_tokens%'

    App\State\Provider\RankingProvider:
        arguments:
            $rankingService: '@App\Service\Ranking\RankingServicePostgres'

    App\State\Provider\TournamentListProvider:
        arguments:
            $tournamentListService: '@App\Service\TournamentList\TournamentListServicePostgres'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
